#! /bin/sh
exec ruby -S -x "$0" "$@"
#! ruby

require 'bundler/setup'
Bundler.require
require 'active_support'
require 'active_support/inflector'
require 'active_support/core_ext'
require 'highline/import'


class App
  def self.root
    File.dirname(__FILE__)
  end
end

# initializer
Dir.glob("#{App.root}/config/initializer/*.rb").each do |require_path|
  require require_path
end

# app load
Dir.glob("#{App.root}/app/**/*.rb") do |require_path|
  require require_path
end

# write here
puts Settings.foo.bar
